# Generated by Django 4.2.4 on 2023-08-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=10)),
                ("assignment1", models.CharField(max_length=10)),
                ("assignment2", models.CharField(max_length=10)),
                ("assignment3", models.CharField(max_length=10)),
                ("assignment4", models.CharField(max_length=10)),
                ("assignment5", models.CharField(max_length=10)),
                ("assignment6", models.CharField(max_length=10)),
            ],
        ),
    ]
