# Generated by Django 4.2.4 on 2023-09-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_student_assignment1_alter_student_assignment2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
