# Generated by Django 4.2.4 on 2023-09-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_student_id_alter_student_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="assignment1",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="assignment2",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="assignment3",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="assignment4",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="assignment5",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="assignment6",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
